name: fta
description: Application Flutter pour les Membres de la Food Trucks Association

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.15.0
  flutter_native_splash: ^2.1.6
  firebase_messaging: ^11.2.14
  provider: ^6.0.2
  firebase_auth: ^3.3.15
  cloud_firestore: ^3.1.13
  firebase_storage: ^10.2.13
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5
  image_picker_web: ^2.1.0
  flutter_spinkit: ^5.1.0
  uuid: ^3.0.6
  get: ^4.6.1
  flutter_screenutil: ^5.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0

flutter_icons:
  # flutter pub run flutter_launcher_icons:main
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo-fta-carre.png"

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  # flutter pub run flutter_native_splash:remove

  color: "#42a5f5"
  #background_image: "assets/background.png"
  image: assets/logo-fta-rond.png
  #branding: assets/dart.png
  #branding_mode: bottom

  color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  image_dark: assets/logo-fta-rond.png
  #branding_dark: assets/dart_dark.png

  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/logo-fta-rond.png
    # App icon background color.
    #icon_background_color: "#111111"
    #image_dark: assets/android12splash-invert.png
    #icon_background_color_dark: "#eeeeee"
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo-fta-carre.png
    - assets/logo-fta-rond.png
    - assets/img_not_available.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
