// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkfpHKR3y1nDnIBq_Go--RmGf3pQx3U0g',
    appId: '1:929604283:web:0cbb8a1918008a32087f9e',
    messagingSenderId: '929604283',
    projectId: 'foodtrucks-addict',
    authDomain: 'foodtrucks-addict.firebaseapp.com',
    storageBucket: 'foodtrucks-addict.appspot.com',
    measurementId: 'G-Y5P5W0BPWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKbDwUYts1KbG37w0vzJZvxPR_-Sz0VxY',
    appId: '1:929604283:android:9ec8bede42864f65087f9e',
    messagingSenderId: '929604283',
    projectId: 'foodtrucks-addict',
    storageBucket: 'foodtrucks-addict.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtdU2cg4ya7aFjkbjLWsiu2d3zsium04g',
    appId: '1:929604283:ios:c987f0a726fe6968087f9e',
    messagingSenderId: '929604283',
    projectId: 'foodtrucks-addict',
    storageBucket: 'foodtrucks-addict.appspot.com',
    iosClientId: '929604283-7skke0c94ppivqdbn88f97hs47a44f12.apps.googleusercontent.com',
    iosBundleId: 'com.projetpos.fta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtdU2cg4ya7aFjkbjLWsiu2d3zsium04g',
    appId: '1:929604283:ios:c987f0a726fe6968087f9e',
    messagingSenderId: '929604283',
    projectId: 'foodtrucks-addict',
    storageBucket: 'foodtrucks-addict.appspot.com',
    iosClientId: '929604283-7skke0c94ppivqdbn88f97hs47a44f12.apps.googleusercontent.com',
    iosBundleId: 'com.projetpos.fta',
  );
}
